name: CI Build and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependencias
        run: npm install

      - name: Install Jest y otorgarle permisos de ejecución
        run: npm install --save-dev jest && chmod +x ./node_modules/.bin/jest

      - name: Ejecutar tests
        run: npm test

      - name: Notificar éxito en Slack
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ Build exitosa para *estaciones* en `main`"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notificar error en Slack
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ Falló la build en *estaciones* en `main`"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success() # Sólo se ejecuta si el job 'test' pasó correctamente

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Git para deploy
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # acá va la carpeta con el contenido a subir (si es solo html/js puede ser la raíz o la carpeta build/dist)

      - name: Notificar deploy exitoso en Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"🚀 Deploy realizado correctamente para *estaciones* en `main`"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
